/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xxZQctyMK7c
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Header } from "@/components/ui/header";
import React, { useEffect, useState } from "react";
import { TrashIcon } from "lucide-react";
// @ts-ignore
import Modal from "react-modal";

type ChatRoom = {
  menu: string;
  chatId: number;
  createdAt: string;
};

export default function Main() {
  const [chatRooms, setChatRooms] = useState<ChatRoom[]>([]);
  const router = useRouter();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [chatToDelete, setChatToDelete] = useState<number | null>(null);


  useEffect(() => {
    const fetchChatRooms = async () => {
      try {
        const response = await axios.get("/api/chatrooms");
        setChatRooms(response.data);
      } catch (error) {
        console.error("Error fetching chat rooms:", error);
      }
    };

    fetchChatRooms();
  }, []);

  const handleChatRoomClick = (chatId: number) => {
    router.push(`/chatroom/${chatId}`);
  };

  const handleDeleteClick = async () => {
    try {
      const chatId = chatToDelete;
      console.log(chatId);
      await axios.delete(`/api/chatroom/${chatId}`);
      setChatRooms(chatRooms.filter(chat => chat.chatId !== chatId));
      closeModal();
    } catch (error) {
      console.error("Error deleting chat room:", error);
    }
  };

  const openModal = (chatId: number) => {
    setChatToDelete(chatId);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setChatToDelete(null);
  };

  return (
      <>
        <Header></Header>
        <main className="py-8">
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
            <h1 className="text-6xl font-bold text-red-400 opacity-20">메인페이지</h1>
          </div>
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 gap-6">
              {chatRooms.map((chat, index) => (
                  <Card key={index}>
                    <CardHeader>
                      <CardTitle>{chat.menu}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      {/* Display chat details if selectedChatRoom matches */}
                    </CardContent>
                    <CardFooter className="flex justify-between">
                      <Button variant="outline" onClick={() => handleChatRoomClick(chat.chatId)}>
                        채팅방 보기
                      </Button>
                      <Button variant="outline" className="text-red-500 border-red-500"
                              onClick={() => openModal(chat.chatId)}>
                        <TrashIcon className="h-6 w-6" />
                      </Button>
                    </CardFooter>
                  </Card>
              ))}
            </div>
          </div>
          <div className="fixed bottom-6 right-6">
            <Link href={"/recommend"}>
              <Button size="lg">
                  <PlusIcon className="h-6 w-6" />
                  <span className="sr-only">Add new</span>
              </Button>
            </Link>
          </div>
          {/* 삭제 확인 모달 */}
          <Modal
              isOpen={isModalOpen}
              onRequestClose={closeModal}
              contentLabel="레시피 삭제 확인"
              className="fixed inset-0 flex items-center justify-center z-50 outline-none"
              overlayClassName="fixed inset-0 bg-black bg-opacity-70 z-40"
          >
            {/* 모달 내부 스타일을 JSX 내에서 설정 */}
            <div style={{
              backgroundColor: "#333", /* 검은색 배경색 */
              color: "#fff", /* 텍스트 색상 */
              padding: "20px", /* 내부 간격 설정 */
              borderRadius: "8px" /* 모서리 둥글게 설정 */
            }}>
              <h2 className="text-lg font-semibold mb-4">정말 삭제하시겠습니까?</h2>
              <div className="flex justify-end mt-4">
                <Button variant="outline" onClick={closeModal}>취소</Button>
                <Button variant="outline" className="ml-2 text-red-500 border-red-500" onClick={handleDeleteClick}>네</Button>
              </div>
            </div>
          </Modal>
        </main>
      </>
  )
}

function PlusIcon(props: any) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <path d="M5 12h14" />
        <path d="M12 5v14" />
      </svg>
  )
}