{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-databind",
    "version": "2.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.15.4.jar",
          "url": "jackson-databind-2.15.4.jar",
          "size": 1620433,
          "sha512": "3034623bccd5ed71263eddaab8b4205e71eb63c59769256b64ba87e9a7d4d3d6aa6ccce9facd3538c3e492d9aa00d4df4ab0eddfbe087ed79658672bf13b85f9",
          "sha256": "f99ff7719eef3ee85608b3dee6ecf3c698003fe9d6e34eabbfabccdc9b5ac2c",
          "sha1": "560309fc381f77d4d15c4a4cdaa0db5025c4fd13",
          "md5": "9c7db53b35761e502bc9144008503ad3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.15.4.jar",
          "url": "jackson-databind-2.15.4.jar",
          "size": 1620433,
          "sha512": "3034623bccd5ed71263eddaab8b4205e71eb63c59769256b64ba87e9a7d4d3d6aa6ccce9facd3538c3e492d9aa00d4df4ab0eddfbe087ed79658672bf13b85f9",
          "sha256": "f99ff7719eef3ee85608b3dee6ecf3c698003fe9d6e34eabbfabccdc9b5ac2c",
          "sha1": "560309fc381f77d4d15c4a4cdaa0db5025c4fd13",
          "md5": "9c7db53b35761e502bc9144008503ad3"
        }
      ]
    }
  ]
}
