{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.5.jar",
          "url": "spring-webmvc-6.1.5.jar",
          "size": 1046479,
          "sha512": "404f94b3e323d82ce22826373ec955d7115a3c4b8b40b50947976e52e5a604de32ddd84e57ec30c36e8be0d8a54f52c263f791facf985f5cbff2710fafed5d72",
          "sha256": "f4fbe0c336d4c6b339d84c26418428a34c5e5408321da4e5ab0a5783b1793225",
          "sha1": "92809fce136e0b662dc9325529443386ba5ec2c6",
          "md5": "d45a2fc7dcc2c5639f5c2ac58ac3aa7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.5.jar",
          "url": "spring-webmvc-6.1.5.jar",
          "size": 1046479,
          "sha512": "404f94b3e323d82ce22826373ec955d7115a3c4b8b40b50947976e52e5a604de32ddd84e57ec30c36e8be0d8a54f52c263f791facf985f5cbff2710fafed5d72",
          "sha256": "f4fbe0c336d4c6b339d84c26418428a34c5e5408321da4e5ab0a5783b1793225",
          "sha1": "92809fce136e0b662dc9325529443386ba5ec2c6",
          "md5": "d45a2fc7dcc2c5639f5c2ac58ac3aa7c"
        }
      ]
    }
  ]
}
