{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.10.2.jar",
          "url": "junit-jupiter-api-5.10.2.jar",
          "size": 210956,
          "sha512": "7dfb74405cc011bf0b9176f2093686680225ef32658ec82b55bad9857eb38999b8ac25c23f920127b426120bfc20938f2d9dc8df111a509d9858d350e5ff7685",
          "sha256": "afff77c186cd317275803872fa5133aa801fd6ac40bd91c78a6cf8009b4b17cc",
          "sha1": "fb55d6e2bce173f35fd28422e7975539621055ef",
          "md5": "6e691e23a36de8cbda5cbcc9f31461e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.10.2.jar",
          "url": "junit-jupiter-api-5.10.2.jar",
          "size": 210956,
          "sha512": "7dfb74405cc011bf0b9176f2093686680225ef32658ec82b55bad9857eb38999b8ac25c23f920127b426120bfc20938f2d9dc8df111a509d9858d350e5ff7685",
          "sha256": "afff77c186cd317275803872fa5133aa801fd6ac40bd91c78a6cf8009b4b17cc",
          "sha1": "fb55d6e2bce173f35fd28422e7975539621055ef",
          "md5": "6e691e23a36de8cbda5cbcc9f31461e3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.10.2-javadoc.jar",
          "url": "junit-jupiter-api-5.10.2-javadoc.jar",
          "size": 782409,
          "sha512": "70c2d2bca7ca6d217ff18fbb6b352161788ce19cb6bc0c65888dfce8568964a198eeb3ed19b08afb7ed8a3439294fac343da1b78dfa09b2003a6dbea338be059",
          "sha256": "a4b8d85c2793289909309e8d00c15da7d909fd59aff11f2513eb0100f7c38c3d",
          "sha1": "6b1a9f9714e17d9fe9d55bf74f05f802f3833c2b",
          "md5": "ea87407aa270eb3c12af1f430059d3ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.10.2-sources.jar",
          "url": "junit-jupiter-api-5.10.2-sources.jar",
          "size": 209735,
          "sha512": "c96241f2cb6fe40a3e9b5639eb378ccbfa7d0efe0ffb232856d5248630a8e4a64220bef9aa86f5e38e91cf3e7d8b5926b707769674c20ee7ac7f044336eabda9",
          "sha256": "551e054c2e84b79d087f0410c8e6e3dd3e83ae54129593380d48550da441b5ef",
          "sha1": "b281dbb5921ce56b37b6e07a2502f663ca6c8db6",
          "md5": "b01a0ce6253e3a1393ab26a495f5fe28"
        }
      ]
    }
  ]
}
