{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.4.jar",
          "url": "spring-boot-starter-web-3.2.4.jar",
          "size": 4803,
          "sha512": "07194672e50375dd4f7ca317d89ad39f207bd7382c5ba89d193ca78c4d5a3e59f925a9d8148751b48e096c9c9a50aa78c982a438af3a313d7732ad5d8b6a2fe3",
          "sha256": "603eec34e3ae03e1bf559f1533e834b40c59d20c72b075c46b866555e8697140",
          "sha1": "a74df12b71060da7c8e87f9a8c2ef4ea43fc8017",
          "md5": "e06a41edb2001c5e5427d7342ec387b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.4.jar",
          "url": "spring-boot-starter-web-3.2.4.jar",
          "size": 4803,
          "sha512": "07194672e50375dd4f7ca317d89ad39f207bd7382c5ba89d193ca78c4d5a3e59f925a9d8148751b48e096c9c9a50aa78c982a438af3a313d7732ad5d8b6a2fe3",
          "sha256": "603eec34e3ae03e1bf559f1533e834b40c59d20c72b075c46b866555e8697140",
          "sha1": "a74df12b71060da7c8e87f9a8c2ef4ea43fc8017",
          "md5": "e06a41edb2001c5e5427d7342ec387b6"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.4.jar",
          "url": "spring-boot-starter-web-3.2.4.jar",
          "size": 4803,
          "sha512": "07194672e50375dd4f7ca317d89ad39f207bd7382c5ba89d193ca78c4d5a3e59f925a9d8148751b48e096c9c9a50aa78c982a438af3a313d7732ad5d8b6a2fe3",
          "sha256": "603eec34e3ae03e1bf559f1533e834b40c59d20c72b075c46b866555e8697140",
          "sha1": "a74df12b71060da7c8e87f9a8c2ef4ea43fc8017",
          "md5": "e06a41edb2001c5e5427d7342ec387b6"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.2.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.4.jar",
          "url": "spring-boot-starter-web-3.2.4.jar",
          "size": 4803,
          "sha512": "07194672e50375dd4f7ca317d89ad39f207bd7382c5ba89d193ca78c4d5a3e59f925a9d8148751b48e096c9c9a50aa78c982a438af3a313d7732ad5d8b6a2fe3",
          "sha256": "603eec34e3ae03e1bf559f1533e834b40c59d20c72b075c46b866555e8697140",
          "sha1": "a74df12b71060da7c8e87f9a8c2ef4ea43fc8017",
          "md5": "e06a41edb2001c5e5427d7342ec387b6"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.2.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.4-javadoc.jar",
          "url": "spring-boot-starter-web-3.2.4-javadoc.jar",
          "size": 4742,
          "sha512": "18615a94152368566fb17c01152ef879a9ee1fa1c9eb42337f26f66239fa753fc749ca709435304b38b10449cb7e48d4c7376dbef81687a5f635a0faa726cc0b",
          "sha256": "be869b8fe8fdc9a41f054283393fbfb3c83213627c6690cf7b3cdda53f6d1249",
          "sha1": "abc4f4ddb54d169d4db945341f5d99cc4e366fb1",
          "md5": "98ec3f0a4df2ebc3d06d75feda449951"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.4-sources.jar",
          "url": "spring-boot-starter-web-3.2.4-sources.jar",
          "size": 4740,
          "sha512": "017957a877085de2e1388b025c89d7185c1b445c1b1a7729b97bfa00dc0cba03481df40fbbb059a8911e5f175752c0cb6d3e708b17ac369601559522ba65ae4b",
          "sha256": "fbad529f1aa09baefda43d2ea9d0766cb800d4b8fc849b5c3397ddb89964324c",
          "sha1": "1f2a78be0b860c7a760829ef74a0eab43827641d",
          "md5": "0c28e5012a6df1089577059a4ce6840a"
        }
      ]
    }
  ]
}
