/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6MvJhxnSwIF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import {Header} from "@/components/ui/header";
import {Textarea} from "@/components/ui/textarea";
import {useState} from "react";
import {useRouter} from "next/navigation";
import axios from "axios";

export default function BoardWriting() {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const router = useRouter();

  const handleBoardSave = async ()=>{
    try {
      const response = await axios.post('/api/boards', {
        title: title,
        content: content,
      });
      router.push('/boards');
    }catch (error){
      console.log(error)
    }
  }

  return (
      <>
        <Header></Header>
        <main className="py-8 h-[calc(100vh-72px)]">
          <div className="container mx-auto px-4">
            <div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 h-[300px]">
                <label className="block mb-2 font-bold text-2xl text-white">제목</label>
                <Input className="col-span-full" value={title} onChange={(e)=>(setTitle(e.target.value))}/>
                <label className="block mb-2 font-bold text-2xl text-white">내용</label>
                <div className="col-span-full sm:col-span-2 md:col-span-3 lg:col-span-4">
                  <Textarea className="w-full h-full resize-none" style={{minHeight: '200px', maxHeight: '80vh'}} value={content} onChange={(e)=>(setContent(e.target.value))}/>
                </div>
                <div className="col-span-full flex justify-center gap-2">
                  <Button onClick={()=>(router.push('/boards'))} variant="outline">취소</Button>
                  <Button onClick={handleBoardSave}>저장</Button>
                </div>
              </div>
            </div>
          </div>
        </main>
      </>
  )
}
