{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.10.2.jar",
          "url": "junit-jupiter-params-5.10.2.jar",
          "size": 586027,
          "sha512": "002b2010769413f1bc86cf95a48f679eeb7a372379e8f401f892d03bd1089483937a77f08c095579f81b8f0a27896fac6bebdc4c09a2dff9f5459e09207ac0d8",
          "sha256": "edb1e43ff0b8067626ffb55e5e9eeca1d9ab2478141a7c7f253d115b29cc7cf2",
          "sha1": "359132c82a9d3fa87a325db6edd33b5fdc67a3d8",
          "md5": "2f33df4bff7fbfb15352803fa575b88d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.10.2.jar",
          "url": "junit-jupiter-params-5.10.2.jar",
          "size": 586027,
          "sha512": "002b2010769413f1bc86cf95a48f679eeb7a372379e8f401f892d03bd1089483937a77f08c095579f81b8f0a27896fac6bebdc4c09a2dff9f5459e09207ac0d8",
          "sha256": "edb1e43ff0b8067626ffb55e5e9eeca1d9ab2478141a7c7f253d115b29cc7cf2",
          "sha1": "359132c82a9d3fa87a325db6edd33b5fdc67a3d8",
          "md5": "2f33df4bff7fbfb15352803fa575b88d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.10.2-javadoc.jar",
          "url": "junit-jupiter-params-5.10.2-javadoc.jar",
          "size": 276647,
          "sha512": "450c1cb1c92af422950f45ef22d8a76d582aafe4f8b649f468e706e7ae9f6cf97488bd73b81412b5c93608d28b1d3e82366527ecd21a88085fde2ad89322fa90",
          "sha256": "0774d08de49d2496d227d0cec07baa85057fbfc0f3e52e390b4bc1bf3d4239fc",
          "sha1": "1884958a4a9a9cb99f55d406072cf51348ca764c",
          "md5": "336dab707e32f5362d95d4e272764f1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.10.2-sources.jar",
          "url": "junit-jupiter-params-5.10.2-sources.jar",
          "size": 82905,
          "sha512": "776e597de5a3305f5fdbe33f9d1c948829e544d8e83d32af7f52014b58472a0df1e8cc9f66084301a137bfad056c5ac693fe2e9219ec5359c81d435bd8a15941",
          "sha256": "532dce2ef436152405567ea75f076dc908c4d21641224ecc53913c9f09bfb131",
          "sha1": "1add8e4310a408675f46eae8acafe6b2b72232e5",
          "md5": "df60229724aa09da1bca8d910ac7052d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.10.2.jar",
          "url": "junit-jupiter-params-5.10.2.jar",
          "size": 586027,
          "sha512": "002b2010769413f1bc86cf95a48f679eeb7a372379e8f401f892d03bd1089483937a77f08c095579f81b8f0a27896fac6bebdc4c09a2dff9f5459e09207ac0d8",
          "sha256": "edb1e43ff0b8067626ffb55e5e9eeca1d9ab2478141a7c7f253d115b29cc7cf2",
          "sha1": "359132c82a9d3fa87a325db6edd33b5fdc67a3d8",
          "md5": "2f33df4bff7fbfb15352803fa575b88d"
        }
      ]
    }
  ]
}
