{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jcl",
    "version": "6.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-jcl-6.0.10.jar",
          "url": "spring-jcl-6.0.10.jar",
          "size": 23726,
          "sha512": "8c42ab60f843faf3d98ae0aeb49d8c701dfe62564822a7c1070bcf3f8b7cb6a9197a82c2b83ed2942b34e54f7ef6db469158c5aec274a598e3d26004f47b19e6",
          "sha256": "323209c83374e9e4c0785311334862fef23755b24c3c0ef94af57313336d6c30",
          "sha1": "cba44e98dab40a506c50978a0e5f11ceaa90b3ff",
          "md5": "f143203c66139baf1ee2cf7c6fb78db7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-jcl-6.0.10.jar",
          "url": "spring-jcl-6.0.10.jar",
          "size": 23726,
          "sha512": "8c42ab60f843faf3d98ae0aeb49d8c701dfe62564822a7c1070bcf3f8b7cb6a9197a82c2b83ed2942b34e54f7ef6db469158c5aec274a598e3d26004f47b19e6",
          "sha256": "323209c83374e9e4c0785311334862fef23755b24c3c0ef94af57313336d6c30",
          "sha1": "cba44e98dab40a506c50978a0e5f11ceaa90b3ff",
          "md5": "f143203c66139baf1ee2cf7c6fb78db7"
        }
      ]
    }
  ]
}
