{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.15.4.jar",
          "url": "jackson-datatype-jsr310-2.15.4.jar",
          "size": 121499,
          "sha512": "a415af97ecff72f95dbb8fd5588b9037678a82c18995547af32c13b2e5925e9122ce5bec85cc568e3e1c234d4df85c772ac32ed222822e7384e7006a5c9d2cea",
          "sha256": "efec1b22d14eca2d3c11d57379b5f25784236468ab14509c47d4619325282312",
          "sha1": "89e188c1f6833179309f0fd11a86d426e3f027ea",
          "md5": "f51553de28ff2766f8ae49c34210466c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.15.4.jar",
          "url": "jackson-datatype-jsr310-2.15.4.jar",
          "size": 121499,
          "sha512": "a415af97ecff72f95dbb8fd5588b9037678a82c18995547af32c13b2e5925e9122ce5bec85cc568e3e1c234d4df85c772ac32ed222822e7384e7006a5c9d2cea",
          "sha256": "efec1b22d14eca2d3c11d57379b5f25784236468ab14509c47d4619325282312",
          "sha1": "89e188c1f6833179309f0fd11a86d426e3f027ea",
          "md5": "f51553de28ff2766f8ae49c34210466c"
        }
      ]
    }
  ]
}
