/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ogoON1EGM7K
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import {Input} from "@/components/ui/input";
import {Header} from "@/components/ui/header";

export default function page() {
  return (
    <>
      <Header></Header>
      <main className="py-8">
        <div className="grid grid-cols-1 gap-6">
          <Card className="flex flex-col">
            <CardHeader>
              <CardTitle>레시피 추천</CardTitle>
            </CardHeader>
            <CardContent className="flex-1 space-y-4">
              <div className="flex items-start space-x-4">
                <Avatar>
                  <AvatarImage alt="@jaredpalmer" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback></AvatarFallback>
                </Avatar>
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                    <p>환영합니다! 재료를 인식할 사진을 업로드 해주세요!</p>
                  </div>
                </div>
              </div>
              <div className="flex items-start space-x-4 justify-end">
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-blue-500 text-white p-4">
                    <p>사진 업로드 하기</p>
                    <Input type={"file"}></Input>
                    <div className="flex justify-end">
                      <Button>보내기</Button>
                    </div>
                  </div>
                </div>
                <Avatar>
                  <AvatarImage alt="@you" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>YU</AvatarFallback>
                </Avatar>
              </div>
              <div className="flex items-start space-x-4">
                <Avatar>
                  <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                    <p>인식된 재료는 다음과 같습니다.</p>
                    <p>, , , , , , </p>
                  </div>
                </div>
              </div>
              <div className="flex items-start space-x-4">
                <Avatar>
                  <AvatarImage alt="@maxleiter" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>ML</AvatarFallback>
                </Avatar>
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                    <p>재료를 추가하거나 수정하시겠습니까?</p>
                  </div>
                </div>
              </div>
              <div className="flex items-start space-x-4 justify-end">
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-blue-500 text-white p-4">
                    <div>
                      <Button>예</Button><Button>아니오</Button>
                    </div>
                  </div>
                </div>
                <Avatar>
                  <AvatarImage alt="@you" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>YU</AvatarFallback>
                </Avatar>
              </div>
              <div className="flex items-start space-x-4">
                <Avatar>
                  <AvatarImage alt="@maxleiter" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>ML</AvatarFallback>
                </Avatar>
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                    <p>최종 입력된 재료는 다음과 같습니다.</p>
                    <p>, , , , ,</p>
                  </div>
                </div>
              </div>
              <div className="flex items-start space-x-4">
                <Avatar>
                  <AvatarImage alt="@maxleiter" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>ML</AvatarFallback>
                </Avatar>
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                    <p>해당 재료로 만들 수 있는 음식은 다음과 같습니다.</p>
                    <ol>
                      <li>생선구이</li>
                      <li>미역국</li>
                    </ol>
                    <p>어떤 재료의 음식의 레시피를 보시겠습니까?</p>
                  </div>
                </div>
              </div>
              <div className="flex items-start space-x-4">
                <Avatar>
                  <AvatarImage alt="@maxleiter" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>ML</AvatarFallback>
                </Avatar>
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                    <p>생선 구이의 레시피는 다음과 같습니다.</p>
                    <p>레시피</p>
                    <p>만개의 레시피 링크: </p>
                    <p>저장하시겠습니까?</p>
                  </div>
                </div>
              </div>
              <div className="flex items-start space-x-4 justify-end">
                <div className="flex flex-col space-y-2">
                  <div className="rounded-lg bg-blue-500 text-white p-4">
                    <div>
                      <Button>예</Button><Button>아니오</Button>
                    </div>
                  </div>
                </div>
                <Avatar>
                  <AvatarImage alt="@you" src="/placeholder-avatar.jpg"/>
                  <AvatarFallback>YU</AvatarFallback>
                </Avatar>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="fixed bottom-6 right-6"/>
      </main>
    </>
  )
}

function ClipboardIcon(props) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <rect width="8" height="4" x="8" y="2" rx="1" ry="1"/>
        <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/>
      </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function ScissorsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="6" cy="6" r="3" />
      <path d="M8.12 8.12 12 12" />
      <path d="M20 4 8.12 15.88" />
      <circle cx="6" cy="18" r="3" />
      <path d="M14.8 14.8 20 20" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
