{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "6.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.0.10.jar",
          "url": "spring-core-6.0.10.jar",
          "size": 1817070,
          "sha512": "5e32a26f3a8b550bd987450aeed8c4599ad04cf1ae1501f4240556c588ad9bd1217795ae36174303318ea72e2ef7ff033f67d78f87d14306835767023c1dfa01",
          "sha256": "1c0a6bf9cccfa8bbe6ab49c13963c1abb2edff81d88b1af7462617ddc7c0975d",
          "sha1": "889aa214b6607763ddeb6bd391d682cd71681b36",
          "md5": "5dae840cba7438aae43d780858274e89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.0.10.jar",
          "url": "spring-core-6.0.10.jar",
          "size": 1817070,
          "sha512": "5e32a26f3a8b550bd987450aeed8c4599ad04cf1ae1501f4240556c588ad9bd1217795ae36174303318ea72e2ef7ff033f67d78f87d14306835767023c1dfa01",
          "sha256": "1c0a6bf9cccfa8bbe6ab49c13963c1abb2edff81d88b1af7462617ddc7c0975d",
          "sha1": "889aa214b6607763ddeb6bd391d682cd71681b36",
          "md5": "5dae840cba7438aae43d780858274e89"
        }
      ]
    }
  ]
}
