{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.15.4.jar",
          "url": "jackson-module-parameter-names-2.15.4.jar",
          "size": 9476,
          "sha512": "49268e4318c51ae1ca75210337c0605ce96a8981fa87a816c66875e5b531f7c64fd10a8cb2139d9ebe9f5922f0364d71fc7fdebea41779d5a34e91235981ef9c",
          "sha256": "78e67a9eca8e02e5d8f4e13ed01a10200ab4880720e893f7b04583fbd1c01d31",
          "sha1": "366551e54e2779d5fed140b000c5be7a0b29367d",
          "md5": "a76aaac291aecca676f39aba4e8cdc8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.15.4.jar",
          "url": "jackson-module-parameter-names-2.15.4.jar",
          "size": 9476,
          "sha512": "49268e4318c51ae1ca75210337c0605ce96a8981fa87a816c66875e5b531f7c64fd10a8cb2139d9ebe9f5922f0364d71fc7fdebea41779d5a34e91235981ef9c",
          "sha256": "78e67a9eca8e02e5d8f4e13ed01a10200ab4880720e893f7b04583fbd1c01d31",
          "sha1": "366551e54e2779d5fed140b000c5be7a0b29367d",
          "md5": "a76aaac291aecca676f39aba4e8cdc8a"
        }
      ]
    }
  ]
}
