{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jdk8",
    "version": "2.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.15.4.jar",
          "url": "jackson-datatype-jdk8-2.15.4.jar",
          "size": 35102,
          "sha512": "da0af3c128a266d9f55b4be940a58f0a2c580e922447a1085befb010be4259e750735419032e0a13aa7457c442ff7e814355d9912a8b75518d83628c7a487afc",
          "sha256": "915bed95f06e8f16448652579cea89d336b6ed874ed91081db2c6047f558a673",
          "sha1": "87f2739a96a14c4a7d1b78e09553ae6aded84cf0",
          "md5": "558c62dd303abf30d14bc965ef017c29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.15.4.jar",
          "url": "jackson-datatype-jdk8-2.15.4.jar",
          "size": 35102,
          "sha512": "da0af3c128a266d9f55b4be940a58f0a2c580e922447a1085befb010be4259e750735419032e0a13aa7457c442ff7e814355d9912a8b75518d83628c7a487afc",
          "sha256": "915bed95f06e8f16448652579cea89d336b6ed874ed91081db2c6047f558a673",
          "sha1": "87f2739a96a14c4a7d1b78e09553ae6aded84cf0",
          "md5": "558c62dd303abf30d14bc965ef017c29"
        }
      ]
    }
  ]
}
